### ISSUE TITLE
Enable boxes in custom post types

### ISSUE THREAD

**Issue by reddotrooster** [wpmetabox/meta-box#1187]
Hi I use the Wordress 7 theme. It integrates meta boxes into the theme. I need to find out how to enable existing boxes in custom post types. I was able to do this before by adding my custom post type into line 173 of the metaboxes.php file like this:

```php
$pages_with_basic_meta_boxes = apply_filters( 'presscore_pages_with_basic_meta_boxes', array( 'page', 'post', 'mycustomposttype' ) );
```

Since the meta boxes has upgraded the line of code has changed and I now don't know how to add mycustomposttype. The line of code now looks like this:

```php
$pages_with_basic_meta_boxes = presscore_get_pages_with_basic_meta_boxes();
```

**Comment by rilwis** [comment]
Hi,

We don't have the 7 theme, so it's hard to say. But I'd suggest:

1. Go into the function `presscore_get_pages_with_basic_meta_boxes` to find where it defines meta boxes. If you find a similar code to the previous version, it would be greate.
1. If the code is similar to the previous version, I'd suggest you use this code instead of changing the file directly:

```php
add_filter( 'presscore_pages_with_basic_meta_boxes', function( $post_types ) {
    $post_types[] = 'your_post_type';
    return $post_types;
} );
```

You should put this in a functionality plugin or use [this plugin](https://wordpress.org/plugins/my-custom-functions/) to insert the code. That keeps your code work when the theme updates.

1. If you couldn't find the code similar to the previous one, it seems either it's changed or the author doesn't provide a filter for that. In both cases, you should ask the theme author how to do that.

Hope it helps.
Anh

**Comment by reddotrooster** [comment]
Hi


Thanks for pointing me in the right direction. I managed to find similar code to the previous version in the load-meta-boxes.php file and add the custom post type there


Simon Folbigg



________________________________

**Comment by rilwis** [comment]
Hi Simon,

Glad you figured it out. By the way, you should use filter to add your post type. Otherwise, you modification will be removed when the theme is updated.

**Comment by reddotrooster** [comment]
Thanks

Filter is not something I have attempted before. I have just coded with css before and put it in a child theme. With PHP I presume you can't add these files to a child theme to get it to work in the same way and I need to use Filter?


Thanks


Simon Folbigg
Expat Web Solutions
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

m: +65 97163384 | e: sfolbigg@hotmail.com, simon@expatwebsolutions.com | w. www.expatwebsolutions.com<http://www.expatwebsolutions.com>
Skype: folbiggs | Facebook<http://www.facebook.com/expatwebsolutions.com> | LinkedIn<http://www.linkedin.com/in/simonfolbigg>



________________________________

**Comment by rilwis** [comment]
If you use child theme, you can put the code below in the `functions.php` file and it will work:

```php
add_filter( 'presscore_pages_with_basic_meta_boxes', function( $post_types ) {
    $post_types[] = 'your_post_type';
    return $post_types;
} );
```
