### ISSUE TITLE
error message after update

### ISSUE THREAD

**Issue by webcattivo** [wpmetabox/meta-box#1211]
Hi therem, after an update of the meta-box plugin i get the following error:
Fatal error: Cannot assign by reference to overloaded object in /home/eu229hck/public_html/wp-content/plugins/jekas_extensions/meta-box/extensions/user_meta/meta_box_user.php on line 23

I have not updated to the latest wp version. 

I have the following plugin installed

Contact Form 7Settings 
Cookie NoticeSettings 
Disable CommentsSetting
JEKAS EXTENSIONS
MailChimp for WordPressSettings
Meta BoxEdit 
Redux FrameworkEdit
Simple Universal Google Analytics
Slider RevolutionEdit
Ultimate Coming Soon Page
WP Google MapsEdit
WPML Multilingual CMSActivate
Yoast SEOFAQ 

Can you please help

**Comment by rilwis** [comment]
Hello,

I guess you're using [MB User Meta](https://metabox.io/plugins/mb-user-meta/) inside a plugin Jekas Extensions. So, I think the problem is that the MB User Meta is outdated and not compatible with the current version of Meta Box. Please just update it.

By the way, the file name (`user_meta/meta_box_user.php`) is different from ours. So, there's a chance that this is a custom plugin. If that's the case, please update it to compatible with Meta Box.

**Comment by webcattivo** [comment]
Rilwis, thanks for your prompt reply, I ll try that
