### ISSUE TITLE
Question: validation.min.js doubled up? Or...

### ISSUE THREAD

**Issue by thefrosty** [wpmetabox/meta-box#1372]
## Issue Overview
Looking into the `validation.min.js` BLAME, I see concatenation in 38dd1548b113277402e797d2c0a4997008ce9f1d. This looks like it duplicated the jQuery Validation Plugin v1.19.1 twice (at least the doc blocks). So is this an issue? Currently this seems to be blocking other event listeners on out post forms for invalid checks (we have a special use case for custom select2 unique options, so if needed I can get into more detail on that). 

## Steps to Reproduce (for bugs)
_Will add if question is valid_

### Changing validate.min.js to use: https://github.com/jquery-validation/jquery-validation/blob/1.19.1/dist/jquery.validate.min.js
<img width="936" alt="Screen Shot 2020-05-23 at 8 11 08 AM" src="https://user-images.githubusercontent.com/367897/82734067-23bc6780-9ccd-11ea-8a00-196bcc1c429b.png">

### Not modifying validate.min.js code:
<img width="931" alt="Screen Shot 2020-05-23 at 8 12 40 AM" src="https://user-images.githubusercontent.com/367897/82734087-42baf980-9ccd-11ea-9f0e-58bcc670e3a8.png">

As you can see in the latter photo, there isn't a problem with the last selector, but our event trigger seems to be blocked (which cleans up correct selected selectors on submit)

Our script has a dependency of `rwmb-select2`. Should it be dependent on validate maybe?

#### console.log is never triggered
```js
$(document).on('submit', 'form#post', function (e) {
  console.log(select2UniqueOptions.selectors)
  e.preventDefault()
  // Before submit remove all disabled options to allow data saving.
  select2UniqueOptions.selectors.find('option:disabled').prop('disabled', false).removeData('data')
})
```

**Comment by thefrosty** [comment]
After further investigation, I see that you are combining your validation with the jQuery validate, guess the doc blocks through me off. 

The metabox validation is still blocking my submit event which clears the issues seen in the second screenshot, but would fail because the last module isn't selected.

I am going to see about adding a on event to the `after_validate` hook, but hoping to avoid the need for double clicking submit, or a action loop if I attempt to trigger submit again.

**Comment by rilwis** [comment]
Hi Justin,

Previously, Meta Box loads 3 files for validation: jQuery validation library (which is the file you said about), the additional methods (from jQuery validation lib) and the plugin's `validate.js` file.

In the recent change, we merged 3 files into one single file `validation.min.js`, which is why you see its size is doubled up. The total size doesn't change much but the number of requests reduced.

In the previous version, in Gutenberg, the validation doesn't work and in some case, it doesn't work for HTML5 `required` attributes (which you saw in the 1st screenshot - it's the browser validation, not the plugin's). In the recent version, we make the validation work in both cases (consistently). The red error comes from jQuery validation library, which indicates it works.

The validation script works independently and doesn't depend on `select2`. If you do some custom actions with select2, please try to trigger native `change` event to tell the validation script to re-validate it.

**Comment by thefrosty** [comment]
Okay, the question for the script is valid, thanks for the response. It looks like the additional Validation (latter screenshot) is better at error notices, but now blocks the submit event. I've chosen to add an event check which triggers my custom validation before submit (in this case on #submitdiv hover. 

```js
$(document).on('submit', 'form#post', select2UniqueOptions.removeAllDisabledOptions)
$(document).on('hover', '#submitdiv', select2UniqueOptions.removeAllDisabledOptions)
```

This unblocks me. Closing as this doesn't seem to be an issue, but it would me nice to see a possible trigger action (`before_validate`) like `after_validate`...
