### ISSUE TITLE
Why aren't fields objects?

### ISSUE THREAD

**Issue by funkedgeek** [wpmetabox/meta-box#951]
Always wondered this; why aren't fields used as objects?  It would probably help a lot of ways if we did:
- Proper inheritance and therefore no need for the call function
- No need to pass a field array in many of fields functions because the proper data would be in the object
- Function calls from stored object instead of the class

**Comment by rilwis** [comment]
It was a history reason since the first version. I chose static methods for field class because that makes all the methods are shared between field objects and thus, can save memory.

I understand that field objects can help us a lot at this moment and if we can somehow do that without breaking previous code, then it's a good reason to do.
