### ISSUE TITLE
Possibility to store cloned value as CSV, JSON or multiple entries

### ISSUE THREAD

**Issue by rilwis** [wpmetabox/meta-box#983]
There is a problem of searching/querying the data stored in the database by cloned fields. With the current mechanism of WordPress, the data is always stored as a serialized string, which makes it not queryable.

There was a suggestion of adding a new param to specify the way cloned values is stored for a field, kind of:

`'save_values_as' => 'json|csv|multiple'`

I need more opinions on that. Both the new logic and the param name (if you agree).

And note that when this is implemented in a field, it won't backward compatible with old values.

**Comment by funkedgeek** [comment]
I had suggested that clone fields be saved like multiples a few years back, though it would be serialized if it was both multiple and clone

**Comment by rilwis** [comment]
Agree with serialized if **both** multiple and clone :). There's no other ways to store 2-dimentional arrays.

**Comment by radeno** [comment]
Moving up this issue.
Wordpress default behaviour is storing for multiple meta fields with same key as separate and independent database rows. it has some benefits:

- using standard WP_Query api
- ordered list (every update is removing old meta and save new meta)
- easier to make migrations for old data because no serialized fields
- get_post_meta() returns just simple fundamental objects

I think "clone" and "multiple" have very similar behavior. It is sad that multiple is just for select type.

Currently i need multiple same text field with sorting. But cloning makes everything complex and difficult.

**Comment by rilwis** [comment]
We have implemented [`clone_as_multiple`](https://metabox.io/introducing-clone-as-multiple-feature/). So I think this issue can be closed.
